spring:
    application:
        name: banking-system
    datasource:
        url: jdbc:h2:mem:bankingDB
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        console.enabled: true
    main:
        banner-mode: off
logging:
    level:
        com:
            josko:
                banking: DEBUG
        org:
            springframework: WARN
data:
    path:
        csv:
            customer: ./generated/customers.csv
            account: ./generated/accounts.csv
            transaction: ./generated/transactions.csv
